version: "2"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    restart: unless-stopped
    network_mode: "your-network"
    environment: #AT THIS POINT IT'S ONLY FOR USE TRAEFIK WITH LET'S ENCRYPT AND OVH, IF YOU HAVE ANOTHER PROVIDER PLEASE VISIT THIS PAGE: https://docs.traefik.io/user-guide/examples/#dns-challenge
      - OVH_ENDPOINT=ovh-eu
      - OVH_APPLICATION_KEY=
      - OVH_APPLICATION_SECRET=
      - OVH_CONSUMER_KEY=
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8081'
      - 'traefik.frontend.entryPoints=http,https'
      - 'traefik.frontend.rule=Host:traefik.your-dns.zone'
      - 'traefik.backend=traefik'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/docker/traefik/traefik.toml:/etc/traefik/traefik.toml #TRAEFIK CONFIGURATION FILE
      - /root/docker/traefik/logs:/etc/traefik/logs #LOGS TRAEFIK (DEFINED IN traefik.toml)
      - /root/docker/traefik/acme:/etc/traefik/acme #ACME JSON GENERATED BY LET'S ENCRYPT
      - /root/docker/traefik/rules:/etc/traefik/rules #REVERSE PROXY RULES TO ACCESS EXTERNAL SITE
      - "/etc/localtime:/etc/localtime:ro" #TO HAVE CORRECT TIME INSIDE CONTAINER
