version: "2"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex
    network_mode: "your-network"
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /your/path/plex/config:/config
      - /your/path/plex/temp:/transcode
      - /your/path/plex/data:/data #PATH TO YOUR HOLLIDAYS FILMS :D
    labels:
      - "traefik.port=32400"
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:plex.your-dns.zone'
      - 'traefik.backend=plex'
      - 'traefik.frontend.entryPoints=http,https'
      - "/etc/localtime:/etc/localtime:ro"
